services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: microblog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  microblog:
    depends_on:
      postgres:
        condition:
          service_healthy
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:1234@postgres/microblog
      FLASK_APP: microblog.py
    ports:
      - 8000:5000
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
    mem_limit: 2GB